# Generated by Django 2.1.2 on 2018-10-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=300)),
                ('pmessage', models.CharField(max_length=600)),
                ('pdate', models.DateTimeField()),
                ('plike', models.IntegerField()),
                ('pshare', models.IntegerField()),
                ('pview', models.IntegerField()),
            ],
        ),
    ]
