# Generated by Django 2.1 on 2019-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0002_auto_20181212_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpost',
            name='pcomment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
