# Generated by Django 2.1 on 2019-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0003_fbpost_pcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='pshare',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fbpost',
            name='pview',
            field=models.IntegerField(null=True),
        ),
    ]
