# Generated by Django 2.1 on 2019-01-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0004_auto_20190103_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='pshare',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbpost',
            name='pview',
            field=models.IntegerField(default=0),
        ),
    ]
