# Generated by Django 2.1 on 2019-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0006_auto_20190103_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='pshare',
            field=models.IntegerField(null=True),
        ),
    ]
