# Generated by Django 2.1 on 2019-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0007_auto_20190103_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='pview',
            field=models.IntegerField(null=True),
        ),
    ]
