# Generated by Django 2.1 on 2019-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0008_auto_20190103_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='pdate',
            field=models.TextField(max_length=300),
        ),
    ]
