# Generated by Django 2.1 on 2019-02-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0009_auto_20190226_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='plike',
            field=models.TextField(max_length=100),
        ),
    ]
