# Generated by Django 2.1 on 2019-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookdata', '0010_auto_20190226_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpost',
            name='pcomment',
            field=models.TextField(max_length=100),
        ),
    ]
